table dim_stations
	lineageTag: 8c500ed5-c411-4bf5-bea2-1f903568c12f

	column station_id
		dataType: int64
		formatString: 0
		lineageTag: 40476320-5c96-480c-b5c7-41a25026a28c
		summarizeBy: sum
		sourceColumn: station_id

		annotation SummarizationSetBy = Automatic

	column station_name
		dataType: string
		lineageTag: 99d800ce-ab47-4d52-a926-3529c630c0fd
		summarizeBy: none
		sourceColumn: station_name

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: int64
		formatString: 0
		lineageTag: 8c835d8c-f0b2-475c-8ff0-2f858ce0437e
		summarizeBy: none
		sourceColumn: line_id

		annotation SummarizationSetBy = Automatic

	column line_name
		dataType: string
		lineageTag: 5c1a95cb-8397-4901-a1f2-8ad539d4bbe2
		summarizeBy: none
		sourceColumn: line_name

		annotation SummarizationSetBy = Automatic

	column is_interchange
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1bdf72d9-0650-4f40-a751-3a393dfcd3e0
		summarizeBy: none
		sourceColumn: is_interchange

		annotation SummarizationSetBy = Automatic

	partition dim_stations = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Code_projects\PowerBi & Excel\dmrc-powerBi\data\dim_stations.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"station_id", Int64.Type}, {"station_name", type text}, {"line_id", Int64.Type}, {"line_name", type text}, {"is_interchange", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

